2024-03-02 18:11:32 :: ERROR :: Функция <function load_from_json at 0x00000294F20B3D80> вызвала исключение Exception
	-> Traceback: "c:\Users\Admin\.projects\trainingbot\app\bot_logging.py:26" in wrapper
Traceback (most recent call last):

  File "c:\Users\Admin\.projects\trainingbot\app\main.py", line 129, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x00000294F3800B80>
    │       └ <function run at 0x00000294EBCA5F80>
    └ <module 'asyncio' from 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x00000294F37B5F00>
           │      └ <function Runner.run at 0x00000294EBD53740>
           └ <asyncio.runners.Runner object at 0x00000294F1F17A40>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\Admin\.projects\trainingbot\app\main.py:28> wait_for=<Future pen...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x00000294EBD513A0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x00000294F1F17A40>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 671, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000294EC20D260>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 638, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000294EBD53100>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1971, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000294EBC95300>
    └ <Handle Task.task_wakeup(<Future finished result=False>)>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=False>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=False>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=False>)>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,)}
                     │    │           │    └ Update(update_id=489764412, message=Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)...
                     │    │           └ <aiogram.client.bot.Bot object at 0x00000294F37EA450>
                     │    └ <function Dispatcher.feed_update at 0x00000294F20128E0>
                     └ <Dispatcher '0x294f37ea510'>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000294F2011080>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000294F37EB380>
                     └ <Dispatcher '0x294f37ea510'>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │       └ Update(update_id=489764412, message=Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x00000294F2080D40>, functools...
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │       └ Update(update_id=489764412, message=Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x00000294F37EB500>, <function TelegramEventObserver...
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │       └ Update(update_id=489764412, message=Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)...
                 └ <function TelegramEventObserver.trigger at 0x00000294F3801F80>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │             └ Update(update_id=489764412, message=Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)...
                 └ <function CallableObject.call at 0x00000294F38509A0>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x294f37ea510'>>, Update(update_id=489764412, messa...
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │    │                           │                  └ Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='pr...
                 │    │                           └ 'message'
                 │    └ <function Router.propagate_event at 0x00000294F2011EE0>
                 └ <Dispatcher '0x294f37ea510'>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='pr...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x00000294F3850860>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000294F2011080>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000294F37EA540>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x00000294F2011F80>
                 └ <Dispatcher '0x294f37ea510'>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                     │        │       └ Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='pr...
                     │        └ <function TelegramEventObserver.trigger at 0x00000294F20111C0>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000294F37EA540>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │             └ Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='pr...
                 └ <function CallableObject.call at 0x00000294F3850CC0>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function log_decorator.<locals>.wrapper at 0x00000294F38018A0>, Message(message_id=385, date=datetime.date...

  File "c:\Users\Admin\.projects\trainingbot\app\bot_logging.py", line 15, in wrapper
    msg = await func(*args)
                │     └ [Message(message_id=385, date=datetime.datetime(2024, 3, 2, 17, 11, 31, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='p...
                └ <function save_user_data.<locals>.wrapper at 0x00000294F3801760>

  File "c:\Users\Admin\.projects\trainingbot\app\save_data.py", line 11, in wrapper
    users_dict = load_from_json(r'app\users.json')
                 └ <function log_non_aiogram.<locals>.wrapper at 0x00000294F20B3EC0>

> File "c:\Users\Admin\.projects\trainingbot\app\bot_logging.py", line 24, in wrapper
    result = func(*args, **kwargs)
             │     │       └ {}
             │     └ ('app\\users.json',)
             └ <function load_from_json at 0x00000294F20B3D80>

  File "c:\Users\Admin\.projects\trainingbot\app\save_data.py", line 44, in load_from_json
    return json.load(json_file)
           │    │    └ <_io.TextIOWrapper name='app\\users.json' mode='r' encoding='utf-8'>
           │    └ <function load at 0x00000294F172EF20>
           └ <module 'json' from 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py'>

  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           │     │  └ <method 'read' of '_io.TextIOWrapper' objects>
           │     └ <_io.TextIOWrapper name='app\\users.json' mode='r' encoding='utf-8'>
           └ <function loads at 0x00000294F172EFC0>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ ''
           │                └ <function JSONDecoder.decode at 0x00000294F172E980>
           └ <json.decoder.JSONDecoder object at 0x00000294F174C770>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ ''
               │    │          │      └ <built-in method match of re.Pattern object at 0x00000294F155B850>
               │    │          └ ''
               │    └ <function JSONDecoder.raw_decode at 0x00000294F172EA20>
               └ <json.decoder.JSONDecoder object at 0x00000294F174C770>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ ''
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-03-02 18:15:40 :: ERROR :: Функция <function load_from_json at 0x00000294F20B3D80> вызвала исключение Exception
	-> Traceback: "c:\Users\Admin\.projects\trainingbot\app\bot_logging.py:26" in wrapper
Traceback (most recent call last):

  File "c:\Users\Admin\.projects\trainingbot\app\main.py", line 129, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x00000294F3800B80>
    │       └ <function run at 0x00000294EBCA5F80>
    └ <module 'asyncio' from 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x00000294F37B5F00>
           │      └ <function Runner.run at 0x00000294EBD53740>
           └ <asyncio.runners.Runner object at 0x00000294F1F17A40>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\Admin\.projects\trainingbot\app\main.py:28> wait_for=<Future pen...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x00000294EBD513A0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x00000294F1F17A40>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 671, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000294EC20D260>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 638, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000294EBD53100>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1971, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000294EBC95300>
    └ <Handle Task.task_wakeup(<Future finished result=False>)>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=False>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=False>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=False>)>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,)}
                     │    │           │    └ Update(update_id=489764414, message=Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)...
                     │    │           └ <aiogram.client.bot.Bot object at 0x00000294F37EA450>
                     │    └ <function Dispatcher.feed_update at 0x00000294F20128E0>
                     └ <Dispatcher '0x294f37ea510'>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000294F2011080>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000294F37EB380>
                     └ <Dispatcher '0x294f37ea510'>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │       └ Update(update_id=489764414, message=Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x00000294F2080D40>, functools...
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │       └ Update(update_id=489764414, message=Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x00000294F37EB500>, <function TelegramEventObserver...
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │       └ Update(update_id=489764414, message=Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)...
                 └ <function TelegramEventObserver.trigger at 0x00000294F3801E40>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │             └ Update(update_id=489764414, message=Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)...
                 └ <function CallableObject.call at 0x00000294F38513A0>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x294f37ea510'>>, Update(update_id=489764414, messa...
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │    │                           │                  └ Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='pr...
                 │    │                           └ 'message'
                 │    └ <function Router.propagate_event at 0x00000294F2011EE0>
                 └ <Dispatcher '0x294f37ea510'>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='pr...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x00000294F38514E0>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000294F2011080>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000294F37EA540>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x00000294F2011F80>
                 └ <Dispatcher '0x294f37ea510'>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                     │        │       └ Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='pr...
                     │        └ <function TelegramEventObserver.trigger at 0x00000294F20111C0>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000294F37EA540>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x294f37ea510'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000294F37EA450>,), 'bot': <aiogra...
                 │             └ Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='pr...
                 └ <function CallableObject.call at 0x00000294F3801BC0>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function log_decorator.<locals>.wrapper at 0x00000294F38018A0>, Message(message_id=388, date=datetime.date...

  File "c:\Users\Admin\.projects\trainingbot\app\bot_logging.py", line 15, in wrapper
    msg = await func(*args)
                │     └ [Message(message_id=388, date=datetime.datetime(2024, 3, 2, 17, 15, 39, tzinfo=TzInfo(UTC)), chat=Chat(id=6876968954, type='p...
                └ <function save_user_data.<locals>.wrapper at 0x00000294F3801760>

  File "c:\Users\Admin\.projects\trainingbot\app\save_data.py", line 11, in wrapper
    users_dict = load_from_json(r'app\users.json')
                 └ <function log_non_aiogram.<locals>.wrapper at 0x00000294F20B3EC0>

> File "c:\Users\Admin\.projects\trainingbot\app\bot_logging.py", line 24, in wrapper
    result = func(*args, **kwargs)
             │     │       └ {}
             │     └ ('app\\users.json',)
             └ <function load_from_json at 0x00000294F20B3D80>

  File "c:\Users\Admin\.projects\trainingbot\app\save_data.py", line 44, in load_from_json
    return json.load(json_file)
           │    │    └ <_io.TextIOWrapper name='app\\users.json' mode='r' encoding='utf-8'>
           │    └ <function load at 0x00000294F172EF20>
           └ <module 'json' from 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py'>

  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           │     │  └ <method 'read' of '_io.TextIOWrapper' objects>
           │     └ <_io.TextIOWrapper name='app\\users.json' mode='r' encoding='utf-8'>
           └ <function loads at 0x00000294F172EFC0>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ ''
           │                └ <function JSONDecoder.decode at 0x00000294F172E980>
           └ <json.decoder.JSONDecoder object at 0x00000294F174C770>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ ''
               │    │          │      └ <built-in method match of re.Pattern object at 0x00000294F155B850>
               │    │          └ ''
               │    └ <function JSONDecoder.raw_decode at 0x00000294F172EA20>
               └ <json.decoder.JSONDecoder object at 0x00000294F174C770>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ ''
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
